sudo: false

matrix:
  include:
  - os: linux
  - os: osx

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/${TRAVIS_OS_NAME}-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
- travis_wait stack --no-terminal --skip-ghc-check --copy-bins --test build
- fregot test tests/rego
- fspec -j2 --pretty-diff tests/golden
