resolver: 'lts-19.12'

# Dev options
ghc-options:
  fregot: -freverse-errors

packages:
- '.'

extra-deps:
- './packages/pcre-simple'
- 'goldplate-0.2.0'
- git: 'https://github.com/jaspervdj/glob-intersection.git'
  commit: '8f06cb21d4943e7473f7a41e4e621fa5d51e9606'

nix:
  packages: ['zlib.dev', 'zlib.out']
