resolver: 'lts-18.21'

# Dev options
ghc-options:
  fregot: -freverse-errors

packages:
- '.'

extra-deps:
- './packages/pcre-simple'
- git: https://github.com/fugue/goldplate.git
  commit: d799f3a88f50f79a080da9444853a7708d9b417f

nix:
  packages: ['zlib.dev', 'zlib.out']
