resolver: 'lts-15.6'

# Dev options
ghc-options:
  fregot: -freverse-errors

packages:
- '.'

extra-deps:
- './packages/pcre-simple'
- './packages/hs-jose'
- 'HsYAML-0.2.1.0'
- git: https://github.com/fugue/goldplate.git
  commit: 0ac9d399eb7bcac810a1bf4d97ccc08fe6f39f39

nix:
  packages: ["zlib.dev", "zlib.out"]
